// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChatUsersResponse struct {
	MessageUser   string `json:"messageUser"`
	LatestMessage string `json:"latestMessage"`
}

type DirectMessagesResponse struct {
	Element string `json:"element"`
	RoomID  int    `json:"roomID"`
	User    *User  `json:"user"`
}

type User struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	Image *string `json:"image"`
}
