// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type ChatUsersResponse struct {
	User          *User  `json:"user"`
	LatestMessage string `json:"latestMessage"`
}
