name: Deploy to Cloud Run

on:
  push:
    # branches:
    #   - deploy-ci
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Authenticate to Google Cloud 
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_NUM }}/locations/global/workloadIdentityPools/${{ secrets.POOL_ID }}/providers/${{ secrets.PROVIDER_ID }}'
          service_account: tnamba-tutorial-ga-sa@tech-lab-323207.iam.gserviceaccount.com

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tnamba-tutorial-sidecar \
            --image=gcr.io/tech-lab-323207/pro-traning-b:latest \
            --region=asia-northeast1 \
            --project=tech-lab-323207 \
            --platform=managed 